### ISSUE TITLE
Make locally runnable Flutter engine symbolication tool 

### ISSUE THREAD

**Issue by jmagman** [flutter-symbolizer-bot/flutter-symbolizer-bot#4]
@mraleph says the bot has fallen over:

>  the bot probably fell over because nobody maintains it. I think it might be easiest if we massage the code base a bit and make it local tool instead - then it would be easier to maintain and detect when things go wrong. 

https://github.com/flutter/flutter/issues/141351#issuecomment-1904669776

1. Make the tool runnable locally
2. Update the Flutter docs for instructions on using it https://github.com/flutter/flutter/wiki/Crashes

**Comment by jmagman** [comment]
@mraleph where does the symbolication code live that would need to be refactored to run locally?

**Comment by mraleph** [comment]
The code lives here: https://github.com/dart-lang/dart_ci/tree/main/github-label-notifier/symbolizer

It's already runnable locally - but might need a bit more refinement. It's a bit too tiered towards bot-comment-like output.

**Comment by mraleph** [comment]
This is done now and README.md is updated to reflect that symbolizer-bot is kinda dead.

Instructions for local usage are given here: https://github.com/dart-lang/dart_ci/blob/main/github-label-notifier/symbolizer/README.md#using-this-locally

**Comment by mraleph** [comment]
Also fyi @aam @rmacnak-google as the most recent users

**Comment by jmagman** [comment]
I updated the Flutter crashes wiki to point to that README https://github.com/flutter/flutter/wiki/Crashes
